def refresh_mtoon1_outline(material_name: str) -> set[str]: ...
def update_spring_bone1_animation(delta_time: float = 1) -> set[str]: ...
def add_spring_bone1_spring(armature_name: str) -> set[str]: ...
def add_spring_bone1_spring_joint(
    armature_name: str,
    spring_index: int,
) -> set[str]: ...
def bones_rename(armature_name: str) -> set[str]: ...
def load_human_bone_mappings(filepath: str) -> set[str]: ...
def save_human_bone_mappings(filepath: str) -> set[str]: ...
def model_validate(
    execution_context: str = "EXEC_DEFAULT",
    show_successful_message: bool = False,
    armature_object_name: str = "",
) -> set[str]: ...
def assign_vrm0_humanoid_human_bones_automatically(armature_name: str) -> set[str]: ...
def assign_vrm1_humanoid_human_bones_automatically(armature_name: str) -> set[str]: ...
